/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (master) -  9 Oct 2020 17:47
*/
#include "stdio.h"
#include "stdlib.h"
#include "time.h"

/*
  Differentiation of conv in reverse (adjoint) mode (with options i4 dr8 r4):
   gradient     of useful results: *c
   with respect to varying inputs: *a *b *c
   RW status of diff variables: a:(loc) *a:out b:(loc) *b:out
                c:(loc) *c:in-out
   Plus diff mem management of: a:in b:in c:in
*/
void conv_b(float *a, float *ab, int Na, float *b, float *bb, int Nb, float *cb) {
    int Nc = Na + Nb - 1;
    *ab = 0.0;
    *bb = 0.0;
    for (int ib = Nb-1; ib > -1; --ib)
        for (int ia = Na-1; ia > -1; --ia) {
            bb[ib] = bb[ib] + a[ia]*cb[ib+ia];
            ab[ia] = ab[ia] + b[ib]*cb[ib+ia];
        }
}

void conv (float *a, int Na, float *b, int Nb, float *c)
{
    int Nc = Na + Nb - 1;
    for (int ib = 0; ib < Nb; ib++) {
        for (int ia = 0; ia < Na; ia++) {
            c[ib + ia] = c[ib + ia] + b[ib] * a[ia];
        };
    };
};

float dot_prod (float *a, float *b, int N) {
    float sum = 0.0;
    for (int i = 0; i < N; i++) {
        sum += a[i] * b[i];
    };
    return sum;
};

int main(int argc, char **argv)
{
    int N = 1000;
    int Nc = 2*N - 1;
    float* a = (float*)malloc(N  * sizeof(float));
    float* b = (float*)malloc(N  * sizeof(float));
    float* c = (float*)malloc(Nc * sizeof(float));

    float* ab = (float*)malloc(N  * sizeof(float));
    float* bb = (float*)malloc(N  * sizeof(float));
    float* cb = (float*)malloc(Nc * sizeof(float));

    srand(time(0));

    for (int i = 0; i < N; i++) {
        a[i] = (float)rand()/(float)(RAND_MAX/1.);
        b[i] = (float)rand()/(float)(RAND_MAX/1.);
        ab[i] = 0.0;
        bb[i] = 0.0;
    };
    for (int i = 0; i < Nc; i++) {
        c[i] = (float)rand()/(float)(RAND_MAX/1.);
        cb[i] = 0;
    };

    conv(a, N, b, N, cb);
    conv_b(a, ab, N, b, bb, N, cb);

    float test1 = dot_prod(a, ab, N);
    float test2 = dot_prod(b, bb, N);
    float test3 = dot_prod(c, cb, N);

    printf("test1 = %e, test2 = %e, test3 = %e", test1, test2, test3);
    printf("difference = %e", (test3 - test2)/test3);
    printf("difference = %e", (test3 - test1)/test3);

    return 0;
};
