/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (master) -  9 Oct 2020 17:47
*/
#include <adBuffer.h>

/*
  Differentiation of ForwardVTI in reverse (adjoint) mode (with options i4 dr8 r4):
   gradient     of useful results: **u1 **u2
   with respect to varying inputs: **vp **u0 **u1 **u2
   RW status of diff variables: vp:(loc) *vp:(loc) **vp:out u0:(loc)
                *u0:(loc) **u0:out u1:(loc) *u1:(loc) **u1:incr
                u2:(loc) *u2:(loc) **u2:in-out
   Plus diff mem management of: vp:in *vp:in u0:in *u0:in u1:in
                *u1:in u2:in *u2:in
*/
void ForwardVTI_b(float **vp, float **vpb, float **u0, float **u0b, float **u1
        , float **u1b, float **u2, float **u2b) {
    const int x_M, x_m, y_M, y_m, p_rec_M, p_rec_m, p_src_M, p_src_m, time_M, 
    time_m, nthreads, nthreads_nonaffine;
    float **epsilon, **delta, **damp, **src_coords, **src;
    const float dt, o_x, o_y;
    float r0 = 1.0F/(dt*dt);
    float r1 = 1.0F/dt;
    int time = 10;
    int branch;
    for (int x = x_m; x < x_M+1; ++x)
        for (int y = y_m; y < y_M+1; ++y) {
            float r14 = -6.24999986e-3F*u0[x+4][y+4];
            float r13 = 2.0F*epsilon[x+4][y+4];
            float r12 = 1.25e-1F*u0[x+4][y+2] - u0[x + 4][y + 3] + u0[x + 4][y
            + 5] - 1.25e-1F*u0[x+4][y+6];
            float r11 = 1.25e-1F*u0[x+2][y+4] - u0[x + 3][y + 4] + u0[x + 5][y
            + 4] - 1.25e-1F*u0[x+6][y+4];
            float r10 = 1.0F/(vp[x+4][y+4]*vp[x+4][y+4]);
            float r9 = 6.25000009e-3F*u0[x+4][y+2] - 5.0e-2F*u0[x+4][y+3] + 
            5.0e-2F*u0[x+4][y+5] - 6.25000009e-3F*u0[x+4][y+6];
            float r8 = 6.25000009e-3F*u0[x+2][y+4] - 5.0e-2F*u0[x+3][y+4] + 
            5.0e-2F*u0[x+5][y+4] - 6.25000009e-3F*u0[x+6][y+4];
            float r7 = 4.16666673e-3F*u0[x+4][y+2] - 3.33333338e-2F*u0[x+4][y+
            3] + 3.33333338e-2F*u0[x+4][y+5] - 4.16666673e-3F*u0[x+4][y+6];
            float r6 = 2.46913615111777e-6F*(r11*r11)*(r12*r12)*(delta[x+4][y+
            4]-epsilon[x+4][y+4])/(r7*r7*r7*r7+1.97530864e-1F*(r8*r8)*(r9*r9)*
            (r13+2.0F)+1.97530864e-1F*(r8*r8*r8*r8)*(2*epsilon[x+4][y+4]+1.0F)
            +1.19209e-7F);
            pushReal4(r9);
            pushReal4(r8);
            pushReal4(r7);
            pushReal4(r6);
            pushReal4(r14);
            pushReal4(r13);
            pushReal4(r12);
            pushReal4(r11);
            pushReal4(r10);
        }
    {
      /* End section0 
 Begin section1 */
      int chunk_size;
      float arg1;
      UnknownType result1;
      arg1 = 1.0F/3.0F*(p_src_M-p_src_m+1)/nthreads_nonaffine;
      for (int p_src = p_src_m; p_src < p_src_M+1; ++p_src) {
          float posx = -o_x + src_coords[p_src][0];
          float posy = -o_y + src_coords[p_src][1];
          int ii_src_0;
          float arg1;
          UnknownType result1;
          arg1 = 5.0e-2F*posx;
          result1 = floor(arg1);
          ii_src_0 = (int)result1;
          int ii_src_1;
          arg1 = 5.0e-2F*posy;
          result1 = floor(arg1);
          ii_src_1 = (int)result1;
          int ii_src_2;
          arg1 = 5.0e-2F*posy;
          result1 = floor(arg1);
          ii_src_2 = 1 + (int)result1;
          int ii_src_3;
          arg1 = 5.0e-2F*posx;
          result1 = floor(arg1);
          ii_src_3 = 1 + (int)result1;
          float px;
          arg1 = 5.0e-2F*posx;
          result1 = floor(arg1);
          px = (float)(posx-2.0e+1F*(int)result1);
          float py;
          arg1 = 5.0e-2F*posy;
          result1 = floor(arg1);
          py = (float)(posy-2.0e+1F*(int)result1);
          if (ii_src_0 >= x_m - 1 && ii_src_1 >= y_m - 1 && ii_src_0 <= x_M + 
          1 && ii_src_1 <= y_M + 1) {
              float r2 = 0.0;
              pushControl1b(0);
          } else
              pushControl1b(1);
          if (ii_src_0 >= x_m - 1 && ii_src_2 >= y_m - 1 && ii_src_0 <= x_M + 
          1 && ii_src_2 <= y_M + 1) {
              float r3 = 0.0;
              pushControl1b(0);
          } else
              pushControl1b(1);
          if (ii_src_1 >= y_m - 1 && ii_src_3 >= x_m - 1 && ii_src_1 <= y_M + 
          1 && ii_src_3 <= x_M + 1) {
              float r4 = 0.0;
              pushControl1b(0);
          } else
              pushControl1b(1);
          if (ii_src_2 >= y_m - 1 && ii_src_3 >= x_m - 1 && ii_src_2 <= y_M + 
          1 && ii_src_3 <= x_M + 1) {
              float r5 = 0.0;
              pushReal4(py);
              pushReal4(px);
              pushInteger4(ii_src_3);
              pushInteger4(ii_src_2);
              pushInteger4(ii_src_1);
              pushInteger4(ii_src_0);
              pushControl1b(1);
          } else {
              pushReal4(py);
              pushReal4(px);
              pushInteger4(ii_src_3);
              pushInteger4(ii_src_2);
              pushInteger4(ii_src_1);
              pushInteger4(ii_src_0);
              pushControl1b(0);
          }
      }
      **vpb = 0.0;
      for (int p_src = p_src_M; p_src > p_src_m-1; --p_src) {
          float posx;
          float posy;
          int ii_src_0;
          float arg1;
          UnknownType result1;
          int ii_src_1;
          int ii_src_2;
          int ii_src_3;
          float px;
          float py;
          popControl1b(&branch);
          if (branch == 0) {
              popInteger4(&ii_src_0);
              popInteger4(&ii_src_1);
              popInteger4(&ii_src_2);
              popInteger4(&ii_src_3);
              popReal4(&px);
              popReal4(&py);
          } else {
              float r5;
              float r5b = 0.0;
              popInteger4(&ii_src_0);
              popInteger4(&ii_src_1);
              popInteger4(&ii_src_2);
              popInteger4(&ii_src_3);
              popReal4(&px);
              popReal4(&py);
              r5b = u2b[ii_src_3 + 4][ii_src_2 + 4];
              vpb[ii_src_3 + 4][ii_src_2 + 4] = vpb[ii_src_3 + 4][ii_src_2 + 4
                  ] + 2*vp[ii_src_3+4][ii_src_2+4]*px*2.5e-3F*py*(dt*dt)*src[
                  time][p_src]*r5b;
          }
          popControl1b(&branch);
          if (branch == 0) {
              float r4;
              float r4b = 0.0;
              r4b = u2b[ii_src_3 + 4][ii_src_1 + 4];
              vpb[ii_src_3 + 4][ii_src_1 + 4] = vpb[ii_src_3 + 4][ii_src_1 + 4
                  ] + 2*vp[ii_src_3+4][ii_src_1+4]*(dt*dt)*src[time][p_src]*(
                  px*5.0e-2F-px*2.5e-3F*py)*r4b;
          }
          popControl1b(&branch);
          if (branch == 0) {
              float r3;
              float r3b = 0.0;
              r3b = u2b[ii_src_0 + 4][ii_src_2 + 4];
              vpb[ii_src_0 + 4][ii_src_2 + 4] = vpb[ii_src_0 + 4][ii_src_2 + 4
                  ] + 2*vp[ii_src_0+4][ii_src_2+4]*(dt*dt)*src[time][p_src]*(
                  py*5.0e-2F-px*2.5e-3F*py)*r3b;
          }
          popControl1b(&branch);
          if (branch == 0) {
              float r2;
              float r2b = 0.0;
              r2b = u2b[ii_src_0 + 4][ii_src_1 + 4];
              vpb[ii_src_0 + 4][ii_src_1 + 4] = vpb[ii_src_0 + 4][ii_src_1 + 4
                  ] + 2*vp[ii_src_0+4][ii_src_1+4]*(dt*dt)*src[time][p_src]*(
                  px*2.5e-3F*py-px*5.0e-2F-py*5.0e-2F+1)*r2b;
          }
      }
    }
    **u0b = 0.0;
    for (int x = x_M; x > x_m-1; --x)
        for (int y = y_M; y > y_m-1; --y) {
            float r14;
            float r14b = 0.0;
            float r13;
            float r12;
            float r12b = 0.0;
            float r11;
            float r11b = 0.0;
            float r10;
            float r10b = 0.0;
            float r9;
            float r9b = 0.0;
            float r8;
            float r8b = 0.0;
            float r7;
            float r7b = 0.0;
            float r6;
            float r6b = 0.0;
            float temp;
            float temp0;
            float tempb;
            float tempb0;
            float temp1;
            float tempb1;
            float temp2;
            float tempb2;
            float temp3;
            float tempb3;
            popReal4(&r10);
            popReal4(&r11);
            popReal4(&r12);
            popReal4(&r13);
            popReal4(&r14);
            popReal4(&r6);
            popReal4(&r7);
            popReal4(&r8);
            popReal4(&r9);
            temp1 = r1*damp[x+1][y+1] + r0*r10;
            temp0 = r1*damp[x+1][y+1];
            temp = 2.0F*r0*u0[x+4][y+4] - r0*u1[x+4][y+4];
            temp2 = r14 - 2.08333329e-4F*(u0[x+4][y+2]+u0[x+4][y+6]) + 
                3.33333326e-3F*(u0[x+4][y+3]+u0[x+4][y+5]);
            temp3 = r14 - 2.08333329e-4F*(u0[x+2][y+4]+u0[x+6][y+4]) + 
                3.33333326e-3F*(u0[x+3][y+4]+u0[x+5][y+4]);
            tempb = u2b[x+4][y+4]/temp1;
            u2b[x + 4][y + 4] = 0.0;
            u0b[x + 4][y + 4] = u0b[x + 4][y + 4] + (temp0+r0*2.0F*r10)*tempb;
            r10b = (temp-r0*(temp0*u0[x+4][y+4]+r10*temp+(r6+1.0F)*temp2+(r13+
                r6+1.0F)*temp3)/temp1)*tempb;
            u1b[x + 4][y + 4] = u1b[x + 4][y + 4] - r0*r10*tempb;
            r6b = (temp2+temp3)*tempb;
            tempb2 = (r6+1.0F)*tempb;
            tempb3 = (r13+r6+1.0F)*tempb;
            r14b = tempb3 + tempb2;
            u0b[x + 2][y + 4] = u0b[x + 2][y + 4] - 2.08333329e-4F*tempb3;
            u0b[x + 6][y + 4] = u0b[x + 6][y + 4] - 2.08333329e-4F*tempb3;
            u0b[x + 3][y + 4] = u0b[x + 3][y + 4] + 3.33333326e-3F*tempb3;
            u0b[x + 5][y + 4] = u0b[x + 5][y + 4] + 3.33333326e-3F*tempb3;
            temp = 1.97530864e-1F*(2*epsilon[x+4][y+4]+1.0F);
            temp0 = pow(r7, 4) + 1.97530864e-1F*(r13+2.0F)*(r8*r8)*(r9*r9) + 
                temp*pow(r8, 4) + 1.19209e-7F;
            tempb = (delta[x+4][y+4]-epsilon[x+4][y+4])*2.46913615111777e-6F*
                r6b/temp0;
            r11b = 2*r11*(r12*r12)*tempb;
            r12b = 2*r12*(r11*r11)*tempb;
            tempb0 = -(r11*r11*(r12*r12)*tempb/temp0);
            r7b = 4*pow(r7, 3)*tempb0;
            u0b[x + 4][y + 5] = u0b[x + 4][y + 5] + 3.33333326e-3F*tempb2 + 
                3.33333338e-2F*r7b;
            u0b[x + 4][y + 3] = u0b[x + 4][y + 3] + 3.33333326e-3F*tempb2 - 
                3.33333338e-2F*r7b;
            u0b[x + 4][y + 6] = u0b[x + 4][y + 6] - 2.08333329e-4F*tempb2 - 
                4.16666673e-3F*r7b;
            u0b[x + 4][y + 2] = u0b[x + 4][y + 2] + 4.16666673e-3F*r7b - 
                2.08333329e-4F*tempb2;
            tempb1 = (r13+2.0F)*1.97530864e-1F*tempb0;
            r8b = 4*pow(r8, 3)*temp*tempb0 + 2*r8*(r9*r9)*tempb1;
            r9b = 2*r9*(r8*r8)*tempb1;
            u0b[x + 2][y + 4] = u0b[x + 2][y + 4] + 6.25000009e-3F*r8b;
            u0b[x + 3][y + 4] = u0b[x + 3][y + 4] - 5.0e-2F*r8b;
            u0b[x + 5][y + 4] = u0b[x + 5][y + 4] + 5.0e-2F*r8b;
            u0b[x + 6][y + 4] = u0b[x + 6][y + 4] - 6.25000009e-3F*r8b;
            u0b[x + 4][y + 2] = u0b[x + 4][y + 2] + 6.25000009e-3F*r9b;
            u0b[x + 4][y + 3] = u0b[x + 4][y + 3] - 5.0e-2F*r9b;
            u0b[x + 4][y + 5] = u0b[x + 4][y + 5] + 5.0e-2F*r9b;
            u0b[x + 4][y + 6] = u0b[x + 4][y + 6] - 6.25000009e-3F*r9b;
            temp = vp[x + 4][y + 4];
            vpb[x + 4][y + 4] = vpb[x + 4][y + 4] - 2*r10b/pow(temp, 3);
            u0b[x + 2][y + 4] = u0b[x + 2][y + 4] + 1.25e-1F*r11b;
            u0b[x + 3][y + 4] = u0b[x + 3][y + 4] - r11b;
            u0b[x + 5][y + 4] = u0b[x + 5][y + 4] + r11b;
            u0b[x + 6][y + 4] = u0b[x + 6][y + 4] - 1.25e-1F*r11b;
            u0b[x + 4][y + 2] = u0b[x + 4][y + 2] + 1.25e-1F*r12b;
            u0b[x + 4][y + 3] = u0b[x + 4][y + 3] - r12b;
            u0b[x + 4][y + 5] = u0b[x + 4][y + 5] + r12b;
            u0b[x + 4][y + 6] = u0b[x + 4][y + 6] - 1.25e-1F*r12b;
            u0b[x + 4][y + 4] = u0b[x + 4][y + 4] - 6.24999986e-3F*r14b;
        }
}
