/*        Generated by TAPENADE     (INRIA, Ecuador team)
    Tapenade 3.16 (master) -  9 Oct 2020 17:47
*/
/*
  Differentiation of ForwardVTI in forward (tangent) mode (with options i4 dr8 r4):
   variations   of useful results: **u2
   with respect to varying inputs: **vp **u0 **u1
   RW status of diff variables: vp:(loc) *vp:(loc) **vp:in u0:(loc)
                *u0:(loc) **u0:in u1:(loc) *u1:(loc) **u1:in u2:(loc)
                *u2:(loc) **u2:out
   Plus diff mem management of: vp:in *vp:in u0:in *u0:in u1:in
                *u1:in u2:in *u2:in
*/
void ForwardVTI_d(float **vp, float **vpd, float **u0, float **u0d, float **u1
        , float **u1d, float **u2, float **u2d) {
    const int x_M, x_m, y_M, y_m, p_rec_M, p_rec_m, p_src_M, p_src_m, time_M, 
    time_m, nthreads, nthreads_nonaffine;
    float **epsilon, **delta, **damp, **src_coords, **src;
    const float dt, o_x, o_y;
    float r0 = 1.0F/(dt*dt);
    float r1 = 1.0F/dt;
    int time = 10;
    **u2d = 0.0;
    for (int x = x_m; x < x_M+1; ++x)
        for (int y = y_m; y < y_M+1; ++y) {
            float r14 = -6.24999986e-3F*u0[x+4][y+4];
            float r14d = -(6.24999986e-3F*u0d[x+4][y+4]);
            float r13 = 2.0F*epsilon[x+4][y+4];
            float r12 = 1.25e-1F*u0[x+4][y+2] - u0[x + 4][y + 3] + u0[x + 4][y
            + 5] - 1.25e-1F*u0[x+4][y+6];
            float r12d = 1.25e-1F*u0d[x+4][y+2] - u0d[x + 4][y + 3] + u0d[x + 
            4][y + 5] - 1.25e-1F*u0d[x+4][y+6];
            float r11 = 1.25e-1F*u0[x+2][y+4] - u0[x + 3][y + 4] + u0[x + 5][y
            + 4] - 1.25e-1F*u0[x+6][y+4];
            float r11d = 1.25e-1F*u0d[x+2][y+4] - u0d[x + 3][y + 4] + u0d[x + 
            5][y + 4] - 1.25e-1F*u0d[x+6][y+4];
            float temp;
            float temp0;
            float temp1;
            float temp2;
            float temp3;
            float temp4;
            temp = 1.0/(vp[x+4][y+4]*vp[x+4][y+4]);
            float r10 = temp;
            float r10d = -(temp*2*vpd[x+4][y+4]/vp[x+4][y+4]);
            float r9 = 6.25000009e-3F*u0[x+4][y+2] - 5.0e-2F*u0[x+4][y+3] + 
            5.0e-2F*u0[x+4][y+5] - 6.25000009e-3F*u0[x+4][y+6];
            float r9d = 6.25000009e-3F*u0d[x+4][y+2] - 5.0e-2F*u0d[x+4][y+3] +
            5.0e-2F*u0d[x+4][y+5] - 6.25000009e-3F*u0d[x+4][y+6];
            float r8 = 6.25000009e-3F*u0[x+2][y+4] - 5.0e-2F*u0[x+3][y+4] + 
            5.0e-2F*u0[x+5][y+4] - 6.25000009e-3F*u0[x+6][y+4];
            float r8d = 6.25000009e-3F*u0d[x+2][y+4] - 5.0e-2F*u0d[x+3][y+4] +
            5.0e-2F*u0d[x+5][y+4] - 6.25000009e-3F*u0d[x+6][y+4];
            float r7 = 4.16666673e-3F*u0[x+4][y+2] - 3.33333338e-2F*u0[x+4][y+
            3] + 3.33333338e-2F*u0[x+4][y+5] - 4.16666673e-3F*u0[x+4][y+6];
            float r7d = 4.16666673e-3F*u0d[x+4][y+2] - 3.33333338e-2F*u0d[x+4]
            [y+3] + 3.33333338e-2F*u0d[x+4][y+5] - 4.16666673e-3F*u0d[x+4][y+6
            ];
            temp = 2.46913615111777e-6F*(delta[x+4][y+4]-epsilon[x+4][y+4]);
            temp0 = 1.97530864e-1F*(2*epsilon[x+4][y+4]+1.0F);
            temp1 = pow(r7, 4) + 1.97530864e-1F*(r13+2.0F)*(r8*r8)*(r9*r9) + 
                temp0*pow(r8, 4) + 1.19209e-7F;
            temp2 = r11*r11*(r12*r12)/temp1;
            float r6 = temp*temp2;
            float r6d = temp*(r12*r12*2*r11*r11d+r11*r11*2*r12*r12d-temp2*(4*
            pow(r7, 3)*r7d+(r13+2.0F)*1.97530864e-1F*(r9*r9*2*r8*r8d+r8*r8*2*
            r9*r9d)+temp0*4*pow(r8, 3)*r8d))/temp1;
            temp2 = r1*damp[x+1][y+1] + r0*r10;
            temp1 = r1*damp[x+1][y+1];
            temp0 = 2.0F*r0*u0[x+4][y+4] - r0*u1[x+4][y+4];
            temp = r14 - 2.08333329e-4F*(u0[x+4][y+2]+u0[x+4][y+6]) + 
                3.33333326e-3F*(u0[x+4][y+3]+u0[x+4][y+5]);
            temp3 = r14 - 2.08333329e-4F*(u0[x+2][y+4]+u0[x+6][y+4]) + 
                3.33333326e-3F*(u0[x+3][y+4]+u0[x+5][y+4]);
            temp4 = (temp1*u0[x+4][y+4]+r10*temp0+(r6+1.0F)*temp+(r13+r6+1.0F)
                *temp3)/temp2;
            u2d[x + 4][y + 4] = (temp1*u0d[x+4][y+4]+(temp0-temp4*r0)*r10d+r10
                *(r0*2.0F*u0d[x+4][y+4]-r0*u1d[x+4][y+4])+(temp+temp3)*r6d+(r6
                +1.0F)*(r14d-2.08333329e-4F*(u0d[x+4][y+2]+u0d[x+4][y+6])+
                3.33333326e-3F*(u0d[x+4][y+3]+u0d[x+4][y+5]))+(r13+r6+1.0F)*(
                r14d-2.08333329e-4F*(u0d[x+2][y+4]+u0d[x+6][y+4])+
                3.33333326e-3F*(u0d[x+3][y+4]+u0d[x+5][y+4])))/temp2;
            u2[x + 4][y + 4] = temp4;
        }
    {
      /* End section0 
 Begin section1 */
      int chunk_size;
      UnknownType result1;
      result1 = fmax(1, 1.0F/3.0F*(p_src_M-p_src_m+1)/nthreads_nonaffine);
      chunk_size = (int)result1;
      for (int p_src = p_src_m; p_src < p_src_M+1; ++p_src) {
          float posx = -o_x + src_coords[p_src][0];
          float posy = -o_y + src_coords[p_src][1];
          int ii_src_0;
          UnknownType result1;
          result1 = floor(5.0e-2F*posx);
          ii_src_0 = (int)result1;
          int ii_src_1;
          result1 = floor(5.0e-2F*posy);
          ii_src_1 = (int)result1;
          int ii_src_2;
          result1 = floor(5.0e-2F*posy);
          ii_src_2 = 1 + (int)result1;
          int ii_src_3;
          result1 = floor(5.0e-2F*posx);
          ii_src_3 = 1 + (int)result1;
          float px;
          result1 = floor(5.0e-2F*posx);
          px = (float)(posx-2.0e+1F*(int)result1);
          float py;
          result1 = floor(5.0e-2F*posy);
          py = (float)(posy-2.0e+1F*(int)result1);
          if (ii_src_0 >= x_m - 1 && ii_src_1 >= y_m - 1 && ii_src_0 <= x_M + 
          1 && ii_src_1 <= y_M + 1) {
              float temp;
              float temp0;
              temp = 2.5e-3F*px*py - 5.0e-2F*px - 5.0e-2F*py + 1;
              temp0 = dt*dt*src[time][p_src];
              float r2 = temp*(temp0*(vp[ii_src_0+4][ii_src_1+4]*vp[ii_src_0+4
              ][ii_src_1+4]));
              float r2d = temp*temp0*2*vp[ii_src_0+4][ii_src_1+4]*vpd[ii_src_0
              +4][ii_src_1+4];
              u2d[ii_src_0 + 4][ii_src_1 + 4] = u2d[ii_src_0 + 4][ii_src_1 + 4
                  ] + r2d;
              u2[ii_src_0 + 4][ii_src_1 + 4] += r2;
          }
          if (ii_src_0 >= x_m - 1 && ii_src_2 >= y_m - 1 && ii_src_0 <= x_M + 
          1 && ii_src_2 <= y_M + 1) {
              float temp;
              float temp0;
              temp = 5.0e-2F*py - 2.5e-3F*px*py;
              temp0 = dt*dt*src[time][p_src];
              float r3 = temp*(temp0*(vp[ii_src_0+4][ii_src_2+4]*vp[ii_src_0+4
              ][ii_src_2+4]));
              float r3d = temp*temp0*2*vp[ii_src_0+4][ii_src_2+4]*vpd[ii_src_0
              +4][ii_src_2+4];
              u2d[ii_src_0 + 4][ii_src_2 + 4] = u2d[ii_src_0 + 4][ii_src_2 + 4
                  ] + r3d;
              u2[ii_src_0 + 4][ii_src_2 + 4] += r3;
          }
          if (ii_src_1 >= y_m - 1 && ii_src_3 >= x_m - 1 && ii_src_1 <= y_M + 
          1 && ii_src_3 <= x_M + 1) {
              float temp;
              float temp0;
              temp = 5.0e-2F*px - 2.5e-3F*px*py;
              temp0 = dt*dt*src[time][p_src];
              float r4 = temp*(temp0*(vp[ii_src_3+4][ii_src_1+4]*vp[ii_src_3+4
              ][ii_src_1+4]));
              float r4d = temp*temp0*2*vp[ii_src_3+4][ii_src_1+4]*vpd[ii_src_3
              +4][ii_src_1+4];
              u2d[ii_src_3 + 4][ii_src_1 + 4] = u2d[ii_src_3 + 4][ii_src_1 + 4
                  ] + r4d;
              u2[ii_src_3 + 4][ii_src_1 + 4] += r4;
          }
          if (ii_src_2 >= y_m - 1 && ii_src_3 >= x_m - 1 && ii_src_2 <= y_M + 
          1 && ii_src_3 <= x_M + 1) {
              float temp;
              float temp0;
              temp = dt*dt*src[time][p_src];
              temp0 = 2.5e-3F*px*py;
              float r5 = temp*(temp0*(vp[ii_src_3+4][ii_src_2+4]*vp[ii_src_3+4
              ][ii_src_2+4]));
              float r5d = temp*temp0*2*vp[ii_src_3+4][ii_src_2+4]*vpd[ii_src_3
              +4][ii_src_2+4];
              u2d[ii_src_3 + 4][ii_src_2 + 4] = u2d[ii_src_3 + 4][ii_src_2 + 4
                  ] + r5d;
              u2[ii_src_3 + 4][ii_src_2 + 4] += r5;
          }
      }
    }
}
